### ISSUE TITLE
How to keep this updated

### ISSUE THREAD

**Issue by betatim** [jupyterhub/binder-data#2]
The way to keep this updated is to clone it, run the script and then push the updated data file?

**Comment by choldgraf** [comment]
yes :-) 

I already have an issue open saying that we should improve this behavior: https://github.com/jupyterhub/mybinder.org-deploy/issues/345 but I didn't want "perfect" to be come the enemy of "good enough"

**Comment by choldgraf** [comment]
I updated the readme to explain this a bit more clearly

**Comment by betatim** [comment]
👍
